In [3]:
print('Giraffe\nAcademy')

Giraffe
Academy


In [5]:
phrase = 'Giraffe Academy'
print(phrase[0])

G


In [8]:
print(phrase.index('f'))

4


In [9]:
ny_num = -5

In [10]:
print(round(3.7))

4


In [11]:
from math import *

In [12]:
print(floor(3.7)) # lowest

3


In [15]:
print(sqrt(36))

6.0


In [14]:
print(ceil(5.7))

6


In [19]:
name = input('Enter your name: ')
age = input('Enter your age: ')
print("Hello " + name + "! You are " + age)

Enter your name: John
Enter your age: 25
Hello John! You are 25


In [20]:
num1 = input('Enter a number: ')
num2 = input('Enter another number: ')
result = int(num1) + int(num2) #не работает с НЕ целыми числами (типа 5.5)
print(result)

Enter a number: 4
Enter another number: 5
9


In [21]:
num1 = input('Enter a number: ')
num2 = input('Enter another number: ')
result = float(num1) + float(num2) 
print(result)

Enter a number: 4
Enter another number: 5.5
9.5


In [24]:
color = input('Enter a color: ')
plural_noun = input('Enter a Plural Noun: ')
celebrity = input('Enter a celebrity: ')

print('Roses are ' + color)
print(plural_noun + ' are blue')
print('I love ' + celebrity)

Enter a color: Magenta
Enter a Plural Noun: Microwaves
Enter a celebrity: Tom Hanks
Roses are Magenta
Microwaves are blue
I love Tom Hanks


# Lists

In [31]:
friends = ['Kevin', 'Karen', 'Jim', 'Oscar', 'Toby'] #list
print(friends[2])
print(friends[1:])
print(friends[1:3])

Jim
['Karen', 'Jim', 'Oscar', 'Toby']
['Karen', 'Jim']


In [32]:
friends[1] = 'Mike'
print(friends)


['Kevin', 'Mike', 'Jim', 'Oscar', 'Toby']


In [33]:
print(friends[1])

Mike


In [40]:
lucky_numbers = [4, 8, 15, 16, 23, 42]
friends = ['Kevin', 'Karen', 'Jim', 'Oscar', 'Toby']
friends.extend(lucky_numbers)
friends.append('Creed') # add an item in the end of the list
friends.insert(1, 'Kelly') # add an item in the middle of the list (in a certain position)

print(friends)



['Kevin', 'Kelly', 'Karen', 'Jim', 'Oscar', 'Toby', 4, 8, 15, 16, 23, 42, 'Creed']


In [41]:
friends.remove('Jim')
print(friends)

['Kevin', 'Kelly', 'Karen', 'Oscar', 'Toby', 4, 8, 15, 16, 23, 42, 'Creed']


In [42]:
friends.clear() # remove all elements (result = empty list)
print(friends)

[]


In [45]:
friends = ['Kevin', 'Karen', 'Jim', 'Oscar', 'Toby']
friends.pop() # remove the last element in the list
print(friends)

['Kevin', 'Karen', 'Jim', 'Oscar']


In [47]:
print(friends.index('Oscar'))

3


In [51]:
friends = ['Kevin', 'Karen', 'Jim', 'Jim', 'Oscar', 'Toby']

print(friends.count('Jim'))

2


In [54]:
friends.sort() # in alphabetical order
print(friends)

['Jim', 'Jim', 'Karen', 'Kevin', 'Oscar', 'Toby']


In [55]:
lucky_numbers.sort() 
print(lucky_numbers)

[4, 8, 15, 16, 23, 42]


In [56]:
lucky_numbers.reverse() 
print(lucky_numbers)

[42, 23, 16, 15, 8, 4]


In [58]:
friends2 = friends.copy()
print(friends2)

['Jim', 'Jim', 'Karen', 'Kevin', 'Oscar', 'Toby']


# Tuples

In [61]:
coordinates = (4, 5) # tuples can't be changed or modified!
print(coordinates[0])

4


In [62]:
coordinates[0] = 10 # because tuples can NOT be changed
print(coordinates[0])

TypeError: 'tuple' object does not support item assignment

In [63]:
coordinates = [(4, 5), (6, 7), (80, 34)] # list of tuples

# Function

In [67]:
def say_hi():
    print('Hello User')

print('Top')    
say_hi() 
print('Bottom')

Top
Hello User
Bottom


In [71]:
def say_hi(name, age): # parameters in ()
    print('Hello ' + name + '! You are ' + str(age))

say_hi('Mike', 35)
say_hi('Steve', 70) 

Hello Mike! You are 35
Hello Steve! You are 70


In [74]:
def cube(num):
    return num*num*num

result = cube(4)
print(result)

64


# IF statements

In [102]:
is_male = True
is_tall = False

In [103]:
if is_male or is_tall:
    print('You are a male or tall or both')
else:
    print('You are neither male nor tall')

You are a male or tall or both


In [104]:
if is_male and is_tall:
    print('You are a tall male')
else:
    print('You are not a male and not tall')

You are not a male and not tall


In [105]:
if is_male and is_tall:
    print('You are a tall male')
elif is_male and not(is_tall):
    print('You are a short male')
elif not(is_male) and is_tall:
    print('You are not a male but are tall')
else:
    print('You are either not male ot not tall or both')

You are a short male


In [107]:
def max_num(num1, num2, num3):
    if num1 >= num2 and num1 >= num3:
        return num1
    elif num2 >= num1 and num2 >= num3:
        return num2
    else:
        return num3
    
print(max_num(3, 40, 5))

40


== #equal
!= #not equal
>=
<=

In [112]:
num1 = float(input('Enter first number: '))
op = input('Enter operator: ')
num2 = float(input('Enter second number: '))

if op == '+':
    print(num1 + num2)
elif op == '-':
    print(num1 - num2)
elif op == '/':
    print(num1 / num2)
elif op == '*':
    print(num1 * num2)
else:
    print('Invalid operator')

Enter first number: 5
Enter operator: *
Enter second number: 6.7
33.5


# Dictionaries

In [113]:
monthConversions = {
    'Jan': 'January', 
    'Feb': 'February', 
    'Mar': 'March',
    'Apr': 'April',
    'May': 'May',
    'Jun': 'June',
    'Jul': 'July',
    'Aug': 'August',
    'Sept': 'September',
    'Oct': 'October',
    'Nov': 'November',
    'Dec': 'December',
}

print(monthConversions['Nov'])

November


In [114]:
print(monthConversions.get('Dec'))

December


In [115]:
print(monthConversions.get('Luv', 'Not a valid key'))

Not a valid key


# While loop

In [116]:
i = 1
while i <= 10:
    print(i)
    i += 1
    
print('Done with loop')

1
2
3
4
5
6
7
8
9
10
Done with loop


In [117]:
secret_word = 'giraffe'
guess = ''

while guess != secret_word:
    guess = input('Enter guess: ')
print('You win!')    

Enter guess: cat
Enter guess: dad
Enter guess: sad
Enter guess: giraffe
You win!


In [119]:
secret_word = 'giraffe' 
guess = ''
guess_count = 0
guess_limit = 3
out_of_guesses = False

while guess != secret_word and not(out_of_guesses):
    if guess_count < guess_limit:
        guess = input('Enter guess: ')
        guess_count += 1
    else:
        out_of_guesses = True
    
    
if out_of_guesses:
    print('Out of guesses, YOU LOSE!')
else:
    print('You win!') 

Enter guess: car
Enter guess: cat
Enter guess: giraffe
You win!


# FOR loop

In [122]:
for letter in 'Giraffe Academy':
    print(letter)

G
i
r
a
f
f
e
 
A
c
a
d
e
m
y


In [126]:
friends = ['Jim', 'Karen', 'Kevin']
for friend in friends:
    print(friend)

Jim
Karen
Kevin


In [127]:
for index in range(10):
    print(index)

0
1
2
3
4
5
6
7
8
9


In [128]:
for index in range(3, 10): # not uncluding 10
    print(index)

3
4
5
6
7
8
9


In [131]:
friends = ['Jim', 'Karen', 'Kevin']
for index in range((len(friends))):
    print(friends[index])

Jim
Karen
Kevin


In [132]:
for index in range(5):
    if index == 0:
        print('first Iteration')
    else:
        print('Not first')

first Iteration
Not first
Not first
Not first
Not first


# Exponent Function

In [133]:
print(2**3)

8


In [136]:
def raise_to_power(base_num, pow_num):
    result = 1
    for index in range(pow_num):
        result = result * base_num
    return result

print(raise_to_power(2,3))

8


# 2D Lists & Nested Loops

In [141]:
number_grid = [ #lists in lists (grid)
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [0]
]

print(number_grid[2][1])

8


In [143]:
for row in number_grid:
    for col in row:
        print(col)

1
2
3
4
5
6
7
8
9
0


#translator

vowels -> g

dog -> dgg
cat -> cgt

In [145]:
def translate(phrase):
    translation = ''
    for letter in phrase:
        if letter in "AEIOUaeiou":
            translation = translation + 'g'
        else:
            translation = translation + letter
    return translation

print(translate(input('Enter a phrase: ')))

Enter a phrase: to be or not to be
tg bg gr ngt tg bg


In [147]:
def translate(phrase):
    translation = ''
    for letter in phrase:
        if letter.lower() in "aeiou":
            if letter.isupper():
                translation = translation + 'G'
            else:
                translation = translation + 'g'
        else:
            translation = translation + letter
    return translation

print(translate(input('Enter a phrase: ')))

Enter a phrase: On
Gn


# Try Except

In [152]:
try:
    number = int(input('Enter a number: '))
    print(number)
except:
    print('Invalid Input')

Enter a number: jh
Invalid Input


# Reading & Writing

In [ ]:
name_of_the_file = open('name of the file.txt', 'r') #'r' = read = only read; 'w' = write = you can change a file; 'a' = append, you can add new inf; 'r+' = read and write

In [ ]:
name_of_the_file.close()

In [ ]:
name_of_the_file = open('name of the file.txt', 'r')
print(name_of_the_file.readable()) # True/False
print(name_of_the_file.read()) # show all inf in the file
print(name_of_the_file.readline()) #read individual line
print(name_of_the_file.readlines())  # taken each line and put it in an array
print(name_of_the_file.readlines()[1])

In [ ]:
name_of_the_file = open('name of the file.txt', 'r')
for name in name_of_the_file.readlines():
    print(name) #print each line in the file

In [ ]:
name_of_the_file = open('name of the file.txt', 'a') # if 'a' - attach ing in the end of the file, of 'w' - the file will be overwritten
name_of_the_file.write('Toby - Human Resources') 
name_of_the_file.write('\nKelly - Customer Servive') 
name_of_the_file.close()



# Modules and Pip; Classes and Objects

In [157]:
import random

In [158]:
feet_in_mile = 5280
meters_in_kilometer = 1000
beatles= ['John Lennon', 'Paul McCartney', 'George Harrison', 'Ringo Star']

In [ ]:
def get_file_ext(filename):
    return filename[filename.index('.') + 1:]

In [ ]:
def roll_dice(num):
    return random.randint(1, num)

import useful_tools #useful_tools = name of the file
print(useful_tool.roll_dice(10))
#python module index

In [161]:
class Student:
    def __init__(self, name, major, gpa, is_on_probation):
        self.name = name
        self.major - major
        self.gpa = gpa
        self.is_on_probation = is_on_probation       

In [ ]:
from Student import Student # first Student = file, the second = real Student

student1 = Student('Jim', 'Business', 3.1, False) # object = actuall student
student2 = Student('Pam', 'Art', 2.5, True) 

print(student1.name)

# Problems

In [ ]:
# Распродажа
В магазине проходит акция:
На все товары дешевле 1000 рублей скидка 15%
На все товары дороже 1000, но дешевле 5000 рублей скидка 20%
На все товары дороже 5000 рублей скидка 25%
Ввод
Целое неотрицательное число - цена товара в рублях
Вывод
Целое неотрицательное число - скидка на товар в рублях

In [166]:
price = int(input())

if price > 5000:
    print(price * 0.25)
elif price > 1000:
    print(price * 0.20)
else:
    print(price * 0.15)

9500
2375.0


In [ ]:
Напоминание про работу со строками:
len(s) - определить длину строки s
s[i] - получить i-ый символ строки (нумерация с нуля, i - положительное), в случае отрицательного i нумерация идет справа-налево, начиная с -1, например, s[-1] - это последний символ строки
s[i:j] - получить все символы с i-го включительно по j-ый не включительно
s[:i] - все символы до i-го не включительно
s[i:] - все символы, начиная с i-го включительно
s[i:j:k] - все символы с i-го включитель по j-ый не включительно с шагом k, если шаг отрицательный, то i должно указывать на символ стоящий правее, чем j
Задача:
Дана строка.
Сначала выведите третий символ этой строки (считая, что нумерация символов начинается с 1).
Во второй строке выведите предпоследний символ этой строки.
В третьей строке выведите первые пять символов этой строки.
В четвертой строке выведите всю строку, кроме последних двух символов.
В пятой строке выведите все символы с четными индексами (считая, что индексация начинается с 0).
В шестой строке выведите все символы с нечетными индексами (считая, что индексация начинается с 0).
В седьмой строке выведите все символы в обратном порядке.
В восьмой строке выведите все символы строки через один в обратном порядке, начиная с последнего.
В девятой строке выведите длину данной строки.

Ввод:
Abrakadabra
Вывод:
r r
Abrak
Abrakadab
Arkdba
baaar
arbadakarbA
abdkrA
11

In [172]:
word = 'Abrakadabra'
print(word[2])

r


In [179]:
print(len(word))

11


In [173]:
print(word[-2])

r


In [178]:
print(word[:5])

Abrak


In [175]:
print(word[:-2])

Abrakadab


In [182]:
print(word[1:11:2])

baaar


In [183]:
print(word[0:11:2])

Arkdba


In [186]:
print(word[::-1])

arbadakarbA


In [190]:
print(word[::-2])

abdkrA


# 2

In [ ]:
Используя список girls, выведите на экран с помощью срезов следующие списки:
["Виолетта", "Кассандра", "Вирджиния", "Амелия"]
["Вирджиния", "Амелия", "Розамунда", "Янина", "Беатриса"]
["Иветта", "Виолетта", "Вирджиния", "Амелия"]
["Кассандра", "Амелия", "Розамунда"]

In [191]:
girls = ['Ольга', "Иветта", "Виолетта", "Кассандра", "Вирджиния", 
         "Амелия", "Розамунда", "Янина", "Беатриса"]

In [192]:
print(girls[2:6])

['Виолетта', 'Кассандра', 'Вирджиния', 'Амелия']


In [193]:
print(girls[4:])

['Вирджиния', 'Амелия', 'Розамунда', 'Янина', 'Беатриса']


In [199]:
print(girls[1:3] + girls[4:6])

['Иветта', 'Виолетта', 'Вирджиния', 'Амелия']


In [202]:
print(girls[3:4] + girls[5:7])

['Кассандра', 'Амелия', 'Розамунда']


# Задание 4

Реализуйте код для обеих блок-схем в условии задачи
![](https://github.com/rogovich/Data/blob/master/img/1.png?raw=true)

In [207]:
mark = int(input("Введите оценку: "))
if mark < 10:
    print('Это нормально')
elif mark == 10:
    print('Это отлично')

if mark < 6:
    print('Плохо')
    

Введите оценку: 9
Это нормально


![](https://github.com/rogovich/Data/blob/master/img/2.png?raw=true)

In [213]:
mark = int(input("Введите оценку: "))

if mark < 6:
    print('Это плохо')
elif mark < 10:
    print('Это нормально')
elif mark == 10:
    print('Это отлично')   

Введите оценку: 8
Это нормально


# Задание 5
Даны три целых числа. Определите, сколько среди них совпадающих. Программа должна вывести одно из чисел: 3 (если все совпадают), 2 (если два совпадает) или 0 (если все числа различны).
Формат ввода
Вводятся три целых числа
Формат вывода
Целое число

In [221]:
num1 = int(input("Enter number: "))
num2 = int(input("Enter number: "))
num3 = int(input("Enter number: "))

if num1==num2==num3:
    print('3')
elif num1 == num2 or num1==num3 or num2==num3:
    print('2')
else:
    print('0')

Enter number: 1
Enter number: 2
Enter number: 3
0


# 6 
Дано целое число, не меньшее 2. Выведите его наименьший натуральный делитель, отличный от 1.
Формат ввода
Вводится целое положительное число
Формат вывода
Выведите ответ на задачу
Пример
Ввод
15
Вывод
3

In [222]:
x = int(input())
number = 2

while number <= x:
    if x % number == 0:
        print(number)
        break
    else:
        number += 1

15
3


## Задание 7
Вася начал бегать и в первый день он пробежал X километров и выдохся. Вася поставил себе цель Y километров и решил узнать, когда он ее достигнет, если каждый день будет бегать дистанцию на 10% больше, чем в предыдущий.

**Формат ввода**

Программа получает на вход целые числа X, Y

**Формат вывода**

Одно целое число (день, когда Вася пробежит свою цель)


**Примеры**

Ввод:
10
21

Вывод:
9

In [223]:
x = int(input())
y = int(input())
day = 1
while x < y:
    x += 0.1*x
    day += 1
print(day)



10
21
9


## Задание 8

По данному целому числу N распечатайте все квадраты натуральных (целых, положительных) чисел, не превосходящие N, в порядке возрастания. Обратите внимание, что если N является полным квадратом, то его тоже нужно печатать.

**Ввод:**

50

**Вывод:**  
1  
4  
9  
16  
25  
36  
49  

In [224]:
n = int(input())
x = 1
while True:
    x_sq = x ** 2
    if x_sq <= n:
        print(x_sq)
        x += 1    
    else:
        break

50
1
4
9
16
25
36
49


In [225]:
first = [11.25, 18.0, 20.0]
second = [10.75, 9.50]

In [231]:
# Create list areas
areas = [11.25, 18.0, 20.0, 10.75, 9.50]

# Print out the index of the element 20.0
print(areas.index(20.0))

# Print out how often 9.50 appears in areas
print(areas.count(9.50))


2
1


In [233]:
r = 0.43

# Import the math package
import math
math.pi
# Calculate C
C = 2 * pi * r

# Calculate A
A = pi * r ** 2

# Build printout
print("Circumference: " + str(C))
print("Area: " + str(A))

Circumference: 2.701769682087222
Area: 0.5808804816487527


# Задание 10
Последовательность состоит из натуральных чисел, не превосходящих 109, и завершается числом 0. Определите значение наибольшего элемента последовательности.

Вввод: Вводится последовательность целых чисел, оканчивающаяся числом 0 (само число 0 в последовательность не входит, а служит как признак ее окончания).

Вывод: Выведите ответ на задачу.

In [248]:
n_max = int(input())

while True:
    n = int(input())
    
    if n == 0:
        break
    else:
        if n > n_max:
            n_max = n
print(n_max)

7
4
66
0
66


# NUMPY

In [249]:
import numpy as np
scores = np.array([[20, 40, 56, 80, 0, 5, 25, 27, 74, 1],
         [0, 98, 67, 100, 8, 56, 34, 82, 100, 7],
         [78, 54, 23, 79, 100, 0, 0, 42, 95, 83],
         [51, 50, 47, 23, 100, 94, 25, 48, 38, 77],
         [90, 87, 41, 89, 52, 0, 5, 17, 28, 99],
         [32, 18, 21, 18, 29, 31, 48, 62, 76, 22],
         [6, 0, 65, 78, 43, 22, 38, 88, 94, 100],
         [77, 28, 39, 41, 0, 81, 45, 54, 98, 12],
         [66, 0, 88, 0, 44, 0, 55, 100, 12, 11],
         [17, 70, 86, 96, 56, 23, 32, 49, 70, 80],
         [20, 24, 76, 50, 29, 40, 3, 2, 5, 11],
         [33, 63, 28, 40, 51, 100, 98, 87, 22, 30],
         [16, 54, 78, 12, 25, 35, 10, 19, 67, 0],
         [100, 88, 24, 33, 47, 56, 62, 34, 77, 53],
         [50, 89, 70, 72, 56, 29, 15, 20, 0, 0]])

In [250]:
(scores == 0).sum()

13

In [251]:
(scores > 50).sum()

64

In [255]:
((scores >= 50) & (scores < 70)).sum()

23

In [260]:
np.argmax(np.mean(scores, axis=1))+1

10

In [261]:
nonzero = scores[scores > 0]

In [262]:
nonzero.min()

1

In [264]:
advanced = nonzero[nonzero > 80]

In [266]:
advanced.shape

(28,)

In [267]:
advanced.ndim

1

In [268]:
advanced.size

28

In [271]:
sto = advanced == 100
sto

array([False,  True, False,  True,  True, False, False,  True, False,
       False, False, False, False, False, False,  True, False, False,
       False,  True, False, False,  True, False, False,  True, False,
       False])

In [272]:
scores[:7]

array([[ 20,  40,  56,  80,   0,   5,  25,  27,  74,   1],
       [  0,  98,  67, 100,   8,  56,  34,  82, 100,   7],
       [ 78,  54,  23,  79, 100,   0,   0,  42,  95,  83],
       [ 51,  50,  47,  23, 100,  94,  25,  48,  38,  77],
       [ 90,  87,  41,  89,  52,   0,   5,  17,  28,  99],
       [ 32,  18,  21,  18,  29,  31,  48,  62,  76,  22],
       [  6,   0,  65,  78,  43,  22,  38,  88,  94, 100]])

In [275]:
x = np.random.normal (loc=1, scale=10, size=(1000,50)) #генерация случайной матрицы
print(x)

[[  2.71153373  -9.20504283 -13.38763951 ...   9.97495296   2.01261671
   -5.61531925]
 [-25.45028952   1.58274451  -4.70946231 ...   4.49593146  -9.97778601
    9.58026405]
 [  2.65454172   9.97163257  -8.98859548 ...  -3.20557205  -1.71948285
    0.71877695]
 ...
 [  0.36064091   6.48445624  -6.4974684  ...   7.23658143   8.47007073
   -5.01544688]
 [ -8.24735111  -3.77702777  -2.00180987 ...  14.19770444   0.43938892
   -6.68100956]
 [ 25.36814054  14.56895369   0.80312119 ...   2.70477982  -2.77260368
  -19.1289618 ]]


In [277]:
m = np.mean(x, axis=0)
m

array([0.97516208, 1.23023844, 1.13719571, 1.08401444, 1.02716151,
       0.96904133, 0.52163616, 1.25439832, 1.17553435, 1.24855524,
       0.83259522, 1.09754091, 0.99727672, 0.66630202, 0.73824383,
       0.81770511, 0.40305159, 1.51774123, 1.19417558, 1.5603186 ,
       0.66804971, 1.13290302, 0.57202549, 0.93231837, 0.32038648,
       1.08017151, 0.49526943, 0.95808588, 1.19112171, 1.1270842 ,
       0.71994687, 1.22319043, 0.993704  , 1.07139176, 0.8969065 ,
       1.27332922, 0.22136491, 0.95637776, 0.87703421, 0.69716453,
       0.29157417, 1.11954347, 1.33239064, 0.65151163, 0.64453059,
       1.67611231, 1.02911183, 1.28061543, 1.09701053, 0.92254514])

In [278]:
std = np.std(x, axis = 0)
std

array([10.09481425,  9.90569372,  9.78720331,  9.99131863, 10.47606645,
        9.91936531,  9.7109252 , 10.20265984, 10.19298319, 10.37021167,
        9.75973239, 10.02969966, 10.25760983,  9.92051905, 10.49864749,
        9.94999563,  9.9306019 , 10.03634216, 10.14567422,  9.91665382,
        9.86183765,  9.78254744,  9.76120099, 10.4462673 , 10.01808805,
       10.03239993, 10.1185413 , 10.07465808, 10.28527412,  9.97398509,
        9.9986198 ,  9.81807903,  9.92470023,  9.89335822,  9.50871331,
       10.0759289 ,  9.51376236, 10.28030571,  9.99503706,  9.92071075,
       10.10401859,  9.82536994, 10.22168332, 10.40277229, 10.20712252,
        9.61433365, 10.18096926, 10.1439805 , 10.16040344,  9.88728397])

In [279]:
x_norm = ((x-m) / std) # нормировка таблицы
x_norm

array([[ 0.1720063 , -1.05346295, -1.48406391, ...,  0.85709328,
         0.09011514, -0.66123967],
       [-2.61772539,  0.03558621, -0.5973778 , ...,  0.31696788,
        -1.08999575,  0.87564178],
       [ 0.16636063,  0.88246158, -1.03459496, ..., -0.44225119,
        -0.27720291, -0.02060912],
       ...,
       [-0.06087494,  0.53042401, -0.78006596, ...,  0.58714289,
         0.72566609, -0.60056857],
       [-0.91358919, -0.50549375, -0.32072549, ...,  1.27337479,
        -0.06472397, -0.7690236 ],
       [ 2.41638705,  1.34657053, -0.03413381, ...,  0.14039502,
        -0.38085242, -2.02800961]])

In [280]:
Z = np.array([[4, 5, 0], 
             [1, 9, 3],              
             [5, 1, 1],
             [3, 3, 3], 
             [9, 9, 9], 
             [4, 7, 1]])

In [281]:
r = np.sum(Z, axis=1)
print(np.nonzero(r>10))

(array([1, 4, 5]),)


In [282]:
A = np.eye(3)
B = np.eye(3)
print(A)
print(B)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [283]:
AB = np.vstack((A,B))
print(AB)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [290]:
import pandas as pd

In [297]:
df = pd.read_csv('titanic.csv', index_col='PassengerId')
df.head(10)

Survived  Pclass  \
PassengerId                     
1                   0       3   
2                   1       1   
3                   1       3   
4                   1       1   
5                   0       3   
6                   0       3   
7                   0       1   
8                   0       3   
9                   1       3   
10                  1       2   

                                                          Name     Sex   Age  \
PassengerId                                                                    
1                                      Braund, Mr. Owen Harris    male  22.0   
2            Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0   
3                                       Heikkinen, Miss. Laina  female  26.0   
4                 Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0   
5                                     Allen, Mr. William Henry    male  35.0   
6                                             Moran, Mr. James    male   NaN   
7                                      McCarthy, Mr. Timothy J    male  54.0   
8                               Palsson, Master. Gosta Leonard    male   2.0   
9            Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0   
10                         Nasser, Mrs. Nicholas (Adele Achem)  female  14.0   

             SibSp  Parch            Ticket     Fare Cabin Embarked  
PassengerId                                                          
1                1      0         A/5 21171   7.2500   NaN        S  
2                1      0          PC 17599  71.2833   C85        C  
3                0      0  STON/O2. 3101282   7.9250   NaN        S  
4                1      0            113803  53.1000  C123        S  
5                0      0            373450   8.0500   NaN        S  
6                0      0            330877   8.4583   NaN        Q  
7                0      0             17463  51.8625   E46        S  
8                3      1            349909  21.0750   NaN        S  
9                0      2            347742  11.1333   NaN        S  
10               1      0            237736  30.0708   NaN        C

Какое количество мужчин и женщин ехало на корабле? В качестве ответа приведите два числа через пробел.


In [298]:
sex_counts = df['Sex'].value_counts()
print('{} {}'.format(sex_counts['male'], sex_counts['female']))

577 314


Какой части пассажиров удалось выжить? Посчитайте долю выживших пассажиров. Ответ приведите в процентах (число в интервале от 0 до 100, знак процента не нужен), округлив до двух знаков.

In [301]:
survived_df = df['Survived']
count_of_survived = survived_df.value_counts()[1]
survived_percentage = 100.0 * count_of_survived / survived_df.value_counts().sum()
print("{:0.2f}".format(survived_percentage))

38.38


In [303]:
len(df)

891

Какую долю пассажиры первого класса составляли среди всех пассажиров? Ответ приведите в процентах (число в интервале от 0 до 100, знак процента не нужен), округлив до двух знаков.


In [304]:
pclass_df = df['Pclass']
count_first_class_passengers = pclass_df.value_counts()[1]
first_class_percentage = 100.0 * count_first_class_passengers / len(df)
print("{:0.2f}".format(first_class_percentage))

24.24


Какого возраста были пассажиры? Посчитайте среднее и медиану возраста пассажиров. В качестве ответа приведите два числа через пробел.

In [315]:
mean_df = df['Age'].mean()
median_df = df['Age'].median()
print('{:0.2f} {:0.2f}'.format(mean_df, median_df))

29.70 28.00


Коррелируют ли число братьев/сестер/супругов с числом родителей/детей? Посчитайте корреляцию Пирсона между признаками SibSp и Parch.


In [316]:
correlation = df['SibSp'].corr(df['Parch'])
print("{:0.2f}".format(correlation))

0.41


Какое самое популярное женское имя на корабле? Извлеките из полного имени пассажира (колонка Name) его личное имя (First Name). Это задание — типичный пример того, с чем сталкивается специалист по анализу данных. Данные очень разнородные и шумные, но из них требуется извлечь необходимую информацию. Попробуйте вручную разобрать несколько значений столбца Name и выработать правило для извлечения имен, а также разделения их на женские и мужские.

In [320]:
import re

In [326]:
def first_name(name):
    s = re.search('^[^,]+, (.*)', name)
    if s:
        name = s.group(1)

    s = re.search('\(([^)]+)\)', name)
    if s:
        name = s.group(1)

    name = re.sub('(Miss\. |Mrs\. |Ms\. )', '', name)

    name = name.split(' ')[0].replace('"', '')

    return name


names = df[df['Sex'] == 'female']['Name'].map(first_name)
name_counts = names.value_counts()
name_counts.head()
print(name_counts.head(1).index.values[0])

Anna
